#!/usr/bin/env python3
"""Generate the tooltip-gate target registry from the decompiled game tree.

The tooltip hover gate (src/Shell/Sync/TooltipGateAnalysis.cs) transpiles
`Verse.Mouse::IsOver` call sites that an IL analyzer certifies as tooltip-only.
The installer needs a list of types worth reading IL from; this script derives
it mechanically so nobody hand-curates a registry that drifts from the game.

A type qualifies when its source file contains both `Mouse.IsOver(` and
`TipRegion` — the only shape the analyzer can ever certify. `Verse.TooltipHandler`
is excluded because the sink's own mouse gate is what keeps a forced pass from
drawing a real tooltip, and `Verse.Mouse` because rewriting the gate inside the
gate is nonsense. Generic types (Dialog_ManagePolicies<T>,
PawnRoleSelectionWidgetBase<RoleType>) are excluded too: every method they
declare carries unbound type parameters, which the installer refuses to patch,
so listing them buys nothing but a startup warning. Mod decompiles in the same
tree are excluded by namespace: the registry is vanilla only.

Usage: gen_tooltip_gate_targets.py [--stdout]
"""
import os
import re
import sys

DECOMPILED = os.path.expanduser("~/repos/rimworld-access/decompiled")
OUTPUT = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "src", "Shell", "Sync", "TooltipGateTargets.Generated.cs")

VANILLA_ROOTS = ("Verse", "RimWorld", "LudeonTK")
EXCLUDED = frozenset(["Verse.TooltipHandler", "Verse.Mouse"])

NAMESPACE_RE = re.compile(r"^namespace\s+([\w.]+)\s*[;{]?\s*$")
# Top-level types sit at column 0 in the decompiler's output; anything indented
# is nested and reached through GetNestedTypes at runtime instead.
TYPE_RE = re.compile(
    r"^(?:(?:public|internal|sealed|static|abstract|partial|unsafe|readonly|ref)\s+)+"
    r"(?:class|struct|interface|record)\s+([A-Za-z_]\w*)(<)?")


def is_vanilla(namespace):
    return any(namespace == root or namespace.startswith(root + ".")
               for root in VANILLA_ROOTS)


def types_in(path):
    namespace = None
    names = []
    with open(path, "r", encoding="utf-8", errors="replace") as handle:
        for line in handle:
            line = line.rstrip("\n")
            if namespace is None:
                match = NAMESPACE_RE.match(line)
                if match:
                    namespace = match.group(1)
                continue
            match = TYPE_RE.match(line)
            if match and not match.group(2):
                names.append(namespace + "." + match.group(1))
    if namespace is None or not is_vanilla(namespace):
        return []
    return names


def collect():
    found = set()
    for root, dirs, files in os.walk(DECOMPILED):
        dirs[:] = [d for d in dirs if d not in ("bin", "obj", "mods")]
        for name in files:
            if not name.endswith(".cs"):
                continue
            path = os.path.join(root, name)
            with open(path, "r", encoding="utf-8", errors="replace") as handle:
                text = handle.read()
            if "Mouse.IsOver(" not in text or "TipRegion" not in text:
                continue
            found.update(types_in(path))
    return sorted(found - EXCLUDED)


def render(names):
    lines = [
        "// GENERATED by scripts/gen_tooltip_gate_targets.py — do not edit by hand.",
        "// Regenerate after a game update; scripts/check_tooltip_gate_targets.py fails on drift.",
        "",
        "namespace RimWorldAccess.Shell",
        "{",
        "    /// <summary>",
        "    /// Vanilla types whose source registers a tooltip behind its own",
        "    /// <c>Mouse.IsOver</c> guard — the only shape",
        "    /// <see cref=\"TooltipGateAnalysis\"/> can certify. Membership here buys",
        "    /// nothing on its own: every call site still has to pass the analyzer.",
        "    /// </summary>",
        "    public static class TooltipGateTargets",
        "    {",
        "        public static readonly string[] Names =",
        "        {",
    ]
    for name in names:
        lines.append("            \"" + name + "\",")
    lines.extend([
        "        };",
        "    }",
        "}",
        "",
    ])
    return "\n".join(lines)


def main():
    if not os.path.isdir(DECOMPILED):
        sys.stderr.write("decompiled tree not found at " + DECOMPILED + "\n")
        return 1
    text = render(collect())
    if "--stdout" in sys.argv:
        sys.stdout.write(text)
        return 0
    with open(OUTPUT, "w", encoding="utf-8") as handle:
        handle.write(text)
    print("wrote " + OUTPUT)
    return 0


if __name__ == "__main__":
    sys.exit(main())
